### ISSUE TITLE
Unable to read the environment file

### ISSUE THREAD

**Issue by sunscreem** [kilroyweb/homeboy#10]
This package looks great. 

I'm getting the following error however:

```
ROBWORK@ROBWORK-PC MINGW64 /c/www
$ homeboy
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\Users\ROB
WORK\homeboy\.env. in C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Loader.php:75
Stack trace:
#0 C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Loader.php(52): Dotenv\Loader->ensureFileIsReadable()
#1 C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Dotenv.php(91): Dotenv\Loader->load()
#2 C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Dotenv.php(48): Dotenv\Dotenv->loadData()
#3 C:\Users\ROBWORK\homeboy\homeboy(9): Dotenv\Dotenv->load()
#4 {main}
  thrown in C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Loader.php on line 75

Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\Users\ROBWORK\
homeboy\.env. in C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Loader.php:75
Stack trace:
#0 C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Loader.php(52): Dotenv\Loader->ensureFileIsReadable()
#1 C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Dotenv.php(91): Dotenv\Loader->load()
#2 C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Dotenv.php(48): Dotenv\Dotenv->loadData()
#3 C:\Users\ROBWORK\homeboy\homeboy(9): Dotenv\Dotenv->load()
#4 {main}
  thrown in C:\Users\ROBWORK\homeboy\vendor\vlucas\phpdotenv\src\Loader.php on line 75

```

Any ideas what I might need to do?

**Comment by kilroyweb** [comment]
Looks like you just need to copy one of the example .env.example files. Copy and rename it to ".env" and make sure all the info in that file matches up to your current paths.

If you already have a .env file make sure there's no hidden extension (ie .txt) or something else going on that might prevent the system from finding that file

**Comment by sunscreem** [comment]
Ah - am I getting the workflow wrong? I thought you ran homeboy before installing laravel?

**Comment by sunscreem** [comment]
Ignore that. I've seen what you mean now. Duh!
